### ISSUE TITLE
error code 500

### ISSUE THREAD

**Issue by michidk** [mafisz/pagekit-sitemap#1]
Hey, 
i just installed your plugin but if press the "Generate" button, after a couple of seconds it throws the following error:
`vue.js?v=4be3:3 POST https://myDomain.net/admin/sitemap/generate 500 ()(anonymous function) @ vue.js?v=4be3:3r @ vue.js?v=4be3:1t.exports @ vue.js?v=4be3:3t.exports @ vue.js?v=4be3:3(anonymous function) @ vue.js?v=4be3:3`

When i'm trying to visit the /generate site, this is the response:
`No route found for "GET /admin/sitemap/generate": Method Not Allowed (Allow: POST)`

After this, the generated xml looks like that:
`
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>http://myDomain.net/</loc>
    <changefreq>weekly</changefreq>
  </url>`

**Comment by mafisz** [comment]
Is "myDomain.net" your domain?

**Comment by michidk** [comment]
nope, i replaced it because i don't want a backlink from github

**Comment by mafisz** [comment]
It's look like internal server error but i must see what it is.
Can you click generate and see in chrome web tools on network tab, generate preview?

**Comment by michidk** [comment]
![chrome_2016-07-06_11-24-37](https://cloud.githubusercontent.com/assets/3979930/16613435/5f48dfea-436c-11e6-9a4a-95c8b7431292.png)

**Comment by michidk** [comment]
tried it on another pagekit installation which uses the same plugins.. on that installation exactly the same happens...
- Pagekit version: 1.0.3
- Webserver: NGINX
- Database: MySQL 5.5.49-0+deb7u1-log
- PHP Version: 5.5.36

**Comment by mafisz** [comment]
try replace in packages/tomekknapczyk/sitemap/src/Classes/Sitemap.php this:
$this->site = $server_name;
with this:
$this->site = "https://voxvr.brokenvector.net/";
and try

**Comment by mafisz** [comment]
try replace in packages/tomekknapczyk/sitemap/src/Classes/Sitemap.php this:
$this->site = $server_name;
with this:
$this->site = "https://domain.net/";
and try

**Comment by michidk** [comment]
same error

**Comment by mafisz** [comment]
Can you update to 1.0.5, maybe it could help.

**Comment by michidk** [comment]
updated pagekit, reinstalled the sitemap plugin.
Still the same error.

**Comment by mafisz** [comment]
Can you show me screen with result of preview after clicking on red generate like in screen You show before?
![5f48dfea-436c-11e6-9a4a-95c8b7431292](https://cloud.githubusercontent.com/assets/1056554/16615760/269cdad6-4379-11e6-88bf-b98dbae5dd8a.png)
![sitema](https://cloud.githubusercontent.com/assets/1056554/16615764/2b75b1d6-4379-11e6-9932-2d07b915a26b.png)

**Comment by michidk** [comment]
i have an old installation of pagekit which i just updated. I also installed the sitemap plugin and it doesn't work there as well. I think it makes the process a lot easier if you just log into that installation (its an old one i don't use anymore)
_removed_

**Comment by mafisz** [comment]
Ok, try to replace function GetHREFValue in packages/tomekknapczyk/sitemap/src/Classes/Sitemap.php with this:

private function GetHREFValue($anchor)
    {
        $url = '';
        $split1 = explode("href=", $anchor);
        if(count($split1) > 1){
            $split2 = explode(">", $split1[1]);
            $href_string = $split2[0];

```
        if ($href_string[0] == '"')
        {
            $url = $this->GetQuotedUrl($href_string);
        }
        else
        {
            $spaces_split = explode(" ", $href_string);
            $url = $spaces_split[0];
        }
    }
    return $url;
}
```

**Comment by michidk** [comment]
Thanks!
That fixed the issue.

**Comment by mafisz** [comment]
You're welcome:)

**Comment by julianxhokaxhiu** [comment]
I am having the same issue too. If this patch worked, can you please consider pushing a new patched version of your extension?

Thank you and best regards.

---

Pagekit version: 1.0.11
PHP: 5.6.x
Apache 2.x
